### PR TITLE
Mait 3.10

### PR DESCRIPTION
**Pull request by maitbot**
Updated to build with gnuradio 3.10 and pas all tests.

### CODE REVIEW

**Comment by SpontaneousDuck** [comment]
Thanks for the work @maitbot! I was just about to start doing this myself. In the process of building and installing, I did find that. in the GRC files for each block, I needed to update:
```
templates:
  imports: import radar
```
to:
```
templates:
  imports: from gnuradio import radar
```
for each GRC block definition.

**Review by marcusmueller — APPROVED** [review]
Wow. Thank you! Even went in there and fixed things.

**Comment by marcusmueller** [comment]
Can't build GR 3.10 on my laptop right now. @MLsmd, would it be possible that you try building this branch?

**Comment by alphafox02** [comment]
Build completed on 3.10.4 w/ 22.04 python version. However, the one flow graph I opened under examples (examples/simulation/simulator_fmcw_rcs.grc) tossed up just a couple complaints before opening and then I got a module import of 'radar' not found. 

I also had to git checkout the mait/gr-3.10 branch as the default mait-3.10 branch linked above would not built, stopping at GrSwig not found.

**Comment by mbr0wn** [comment]
Merged via #57.

**Pull request closed without merging**
